### ISSUE TITLE
Make install simpler

### ISSUE THREAD

**Issue by tomdeakin** [ukri-excalibur/excalibur-tests#135]
Currently we need to:
1. Install Spack
2. Install ReFrame
3. Create a venv
4. git clone this repo
5. pip install it

It would be good if all we had to do was:

1. git clone this repo
2. Create a venv
3. pip install everything with the right versions including dependencies

We also might want to customise it to hook into existing installs of site-wide Spack.

**Comment by giordano** [comment]
ReFrame is already installed as part of `pip install`: https://github.com/ukri-excalibur/excalibur-tests/blob/6f3cfbd4af8c031986e23af9f8da6360dfee36c5/pyproject.toml#L26  Spack is the main problem, because I think you can only git-clone it to obtain it, if you don't have already an existing installation you can use.

**Comment by tkoskela** [comment]
Hooking into a system-wide spack install is pretty straightforward, and is described in [README](https://github.com/ukri-excalibur/excalibur-tests#spack). You just have to add `spack` to your `PATH`. I suppose you would normally either load a module, or run the `setup-env.sh` script. 

I could try to make the pip installation to check whether `spack` is in `PATH`, and the version is sufficiently new, and prompt the user to install it.

**Comment by tkoskela** [comment]
I'm closing this issue because I don't think we can do much more about it. Adding custom code into pip install is difficult because of security issues. See e.g. [this thread](https://stackoverflow.com/questions/75029388/how-do-i-distribute-fonts-with-my-python-package-using-python-m-build).

If we want to check that spack is available, it should be done during run time.
