### ISSUE TITLE
Keeping outputs and performance logs in seperate repositoy

### ISSUE THREAD

**Issue by draenog** [ukri-excalibur/excalibur-tests#16]
Currently the framework logic code and all outputs and perflogs resulting from runs are kept in the same git repository. This is issue is to discuss possibility of splitting them to a separate repository/repositories.

Pro:
- size of repository for  framework would be smaller and users would have a choice which results they want to download/clone
- submitting and  merging changes to framework code would be easier especially by groups which don't want to make results of all their benchmarks public

Cons:
-  management of repositories become more  complicated, from logical point of view every repository with results should contain framework repository as a submodule which is not compatible with current structure of directories

**Comment by ilectra** [comment]
Benchmark output data files (perflogs, system data and other output) should be somewhere separately from the code used to generate them. Preferably somewhere that can be stored long-term, and others can have access to it, so not only the machine where they were generated on.
- For single benchmark apps, generated and used by a well-defined community, the output data (probably in an adequate summary format) can be stored on a GH repo, together with the scripts that operate on them to generate final reports, visualisations, etc. Eg. https://fenics.github.io/performance-test-results/ .
- For a larger community, that wants to compare benchmark results from different apps at different times, a more scalable solution is needed. The scripts that generate final reports will still sit in their own repo (separate from this one), but the data will be in some other location and the scripts will fetch them when run to generate final reports and plots. That other location has to
  - Have large capacity, cause we don't know how many such studies/benchmarking campaigns people will want to store there
  - Have adequate access control, because some groups might not want to share their data openly immediately. We need to find out what those requirements are. Is it ok, for example, if the whole ExCALIBUR or DiRAC community has access to them but not the general public, or do we need more fine-grained permissions?
- Either way, scripts have to be provided to the users to upload their data to the predefined location (semi-)automatically.

**Comment by ilectra** [comment]
The post-processing scripts have to be in this repo, see https://github.com/ukri-excalibur/excalibur-tests/issues/70 .

**Comment by tkoskela** [comment]
Hosting a repository for performance logs is something we currently don't have the resources for. At the moment we leave storing outputs and managing access to it to the user. We might revisit this in ExCALIBUR 2.
